services:
  client:
    build:
      context: ./Client/
      dockerfile: client.dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4200:4200"
    networks:
      - mynetwork
    image: bmuszynska/client

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7217:7217"
    networks:
      - mynetwork
    image: bmuszynska/api

networks:
  mynetwork: