name: Trigger auto deployment for expensetracker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/expensetracker-AutoDeployTrigger-0924ed6d-9c72-497c-b445-c31fbce4fab0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EXPENSETRACKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EXPENSETRACKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EXPENSETRACKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: expensetrackerregistry.azurecr.io
          registryUsername: ${{ secrets.EXPENSETRACKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EXPENSETRACKER_REGISTRY_PASSWORD }}
          containerAppName: expensetracker
          resourceGroup: ExpenseTracker
          imageToBuild: expensetrackerregistry.azurecr.io/expensetracker:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


